### ISSUE TITLE
Lua error when mousing over currency icons

### ISSUE THREAD

**Issue by robmonte** [brykrys/TooltipItemIcon#3]
The currency icons in the Character page's Currency tab are causing the below Lua error:

```
Message: Interface\AddOns\TooltipItemIcon\TooltipItemIcon-1.795.lua:513: attempt to call field 'GetCurrencyListInfo' (a nil value)
Time: Sat Oct 29 14:12:19 2022
Count: 15
Stack: Interface\AddOns\TooltipItemIcon\TooltipItemIcon-1.795.lua:513: attempt to call field 'GetCurrencyListInfo' (a nil value)
```

**Comment by brykrys** [comment]
I am unable to test as I don't have an Alt with any Currency tokens yet.

Provisional fix in 1.796 based on inspecting Blizzard's token code.

**Comment by robmonte** [comment]
Looks like it worked! I don't get the error anymore and the tooltip now opens. I'll let you decide if you wish to close the issue or not (if you want to test yourself when you get currency, btw honor points are in there too so that's an easy one).

**Comment by brykrys** [comment]
Does the Icon get displayed properly?

1.796 looks for two different functions to find the icon (for WotLK or Retail), but should silently fail (no error but no icon) if it can't find either.

**Comment by robmonte** [comment]
It is displaying for me, yup!

**Comment by brykrys** [comment]
Thank you for confirming :) I'll close it now.
