### ISSUE TITLE
GetAddOnMetadata

### ISSUE THREAD

**Issue by Gennoken** [brykrys/TooltipItemIcon#8]
Hey !

GetAddOnMetadata causing errors as of 10.1, it has been removed from the API.

https://wowpedia.fandom.com/wiki/Patch_10.1.0/API_changes

**Comment by brykrys** [comment]
Had noted this was deprecated, but it's not (yet) causing errors for me.

Had planned to update before the weekend.

If it's producing actual errors, please post them here.

**Comment by brykrys** [comment]
https://github.com/brykrys/TooltipItemIcon/commit/30f7491e25dfeeefbd618ca44c730d23a5ec582a closes issue.
