### ISSUE TITLE
wrong icon on compare tooltips (Currently Equipped item)

### ISSUE THREAD

**Issue by EniacR** [brykrys/TooltipItemIcon#9]
it always show trinket icon on compare tooltips....

**Comment by brykrys** [comment]
It looks like the ShoppingTooltips are getting stuck on the first icon they display.

They do seem to getting cleared correctly. Need to work out where the wrong item is coming from.

**Comment by brykrys** [comment]
Looks like it's a Blizzard bug, where the data used to create the shopping tooltips never gets cleared.

This means the API call to get the current item returns the wrong info (after the first item).

**Comment by brykrys** [comment]
Have checked with WoWUIDev Discord and it does look to be a Blizzard bug.

Root cause dewscribed here https://github.com/Stanzilla/WoWUIBugs/issues/432

Will keep a watch on this to see how quickly it might get fixed.

**Comment by brykrys** [comment]
Checked this in 10.1.5 and it appears to be fixed.
